name: Flutter CI

on:
  pull_request:

jobs:
  analyze:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter: [ '2.8.0' ]
        include:
          - os: ubuntu-latest
            build: apk
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter }}
      - run: flutter pub get
      #      - run: flutter analyze
      #      - run: flutter format --set-exit-if-changed .
      - run: flutter test tests
